### ISSUE TITLE
Online docs are outdated

### ISSUE THREAD

**Issue by huonw** [Kimundi/lazy-static.rs#15]
http://rust-ci.org/Kimundi/lazy-static.rs/doc/lazy_static/

You could consider using travis to update docs hosted on github pages automatically, e.g.

- https://github.com/alexcrichton/git2-rs/blob/master/.travis.yml#L8-L14
- https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example
- https://github.com/huonw/simple_parallel/blob/master/.travis.yml#L6

**Comment by Kimundi** [comment]
When I last set up the doc builds I followed the rust-ci instructions for having the travis build automatically upload the docs to rust-ci - did something break there that makes it no longer work?

**Comment by huonw** [comment]
Yeah, I think they're unreliable.

**Comment by huonw** [comment]
travis-cargo can help with this: https://github.com/huonw/travis-cargo#doc-upload

**Comment by Kimundi** [comment]
Done! :D
