### ISSUE TITLE
error: can't capture dynamic environment in a fn item; use the || { ... } closure form instead

### ISSUE THREAD

**Issue by MarkSwanson** [Kimundi/lazy-static.rs#19]
I'd like to lazily initialize a static CONFIG variable by calling a fn that uses a local var.
I think this might not be possible as I get the error:

error: can't capture dynamic environment in a fn item; use the || { ... } closure form instead

pub fn init() {
 let matches = App::new("test");
  lazy_static! {
        pub static ref CONFIG: Table = || {
            read_config_file(matches).unwrap_or_else(|err| {
                error!("Failed read_config_file(): {}", err.description());
                panic!()
            })
        }();
  }
}

Can I dynamically initialize static variables with data provided by a local variable?

Thanks.

**Comment by MarkSwanson** [comment]
Oh, the macro expands to a fn... which can't close over its environment.
Fwiw this means I can't use lazy_static!{} inside a fn and use local variables in the current environment.

I'm just trying to please hyper as it seems its handlers can only have 'static lifetimes.
I'll have to find another way I think. Closing...

**Comment by MTRNord** [comment]
Can you share what other way you found? I run into the same problem. (I know this is 5 years old)

**Comment by glitzflitz** [comment]
@MTRNord I ran into the same problem too.

**Comment by cherryleafroad** [comment]
I'm trying to do the same thing. Really wish there was a solution here -_-

**Comment by saadziasheikh** [comment]
Anyone found a solution yet??

**Comment by cdecompilador** [comment]
Seems like no solution

**Comment by thingsiplay** [comment]
Seems no solution, it's closed too.

**Comment by amab8901** [comment]
have u guys tried static environment rather than dynamic environment? It's not applicable for my use case (so I won't try it) but perhaps it may be a viable option for some of you?

**Comment by amab8901** [comment]
Idk if my issue is the same as yours but I had a similar issue and I solved it. Here's how:
1) let each environment variable be imported by a dedicated function (func1 for env1, func2 for env2, etc)
2) let all the env-loading functions be called inside a general wrapper function. Create custom return type (struct) for this general wrapper function, where each field is an env.
3) 
```
lazy_static! {
    static ref ENV_VARS: AllEnvVars = read_env().unwrap();
}

fn main() {
    let env_vars = ENV_VARS.clone();
    [... use env var, etc ...]
}
```
