### ISSUE TITLE
Does not seem to work inside submodules

### ISSUE THREAD

**Issue by RenaudParis** [Kimundi/lazy-static.rs#23]
I tried using lazy_static inside a submodule, but nothing happens, my code seems to be never called.

When putting the call to lazy_static in my main.rs file, it works fine though.

Any idea? I tried that only to make my code cleaner, separated into files (a submodule dedicated to define my "global variables" -- because I have no other way to pass them around)

**Comment by Kimundi** [comment]
Hm, strange. The testsuite tests the macro also in a submodule, so that doesn't seem to be an issue.

**Comment by RenaudParis** [comment]
Yes, I surely did something wrong somewhere, that's what I thought when I saw there was 0 issues here :)

I will try to come up with a simple scenario, see if I can reproduce then.

**Comment by RenaudParis** [comment]
Ok I managed to reproduce. I am sure I did something wrong, please forgive me if it is the case.

**Structure**

```Cargo.toml
src/
    main.rs
    app/
        mod.rs
        util/
            mod.rs
            robot.rs
            globals.rs
```

**main.rs**

```#[macro_use]
extern crate lazy_static;

mod app;

struct Human;

impl Human
{
	fn new() -> Human { Human }
	
	fn test(&self)
	{
		println!("I am a human");
	}
}

lazy_static!{
	static ref HUMAN: Human = {
		let mut human = Human::new();
		human
	};
}

fn main()
{
	HUMAN.test();
	ROBOT.test();
}
```

**app/mod.rs**

```
pub mod util;
```

**app/util/mod.rs**

    pub mod robot;
    pub mod globals;

**app/util/robot.rs**

```
pub struct Robot;

impl Robot
{
	pub fn new() -> Robot { Robot }
	
	pub fn test(&self)
	{
		println!("I am a robot");
	}
}
```

**app/util/globals.rs**

```
use lazy_static;

use super::robot::Robot;

lazy_static!{
	pub static ref ROBOT: Robot = {
		let mut robot = Robot::new();
		robot
	};
}
```

When I comment the line ```ROBOT.test();``` , it works fine, but with a warning:

```
warning: static item is never used: 'ROBOT'
```

When I uncomment the line, it fails:

```
error: unresolved name 'ROBOT'
```

Any ideas? For now I am creating my "globals" inside main.rs, it works fine, it is just not ultimately clean. But then again, I have only been at Rust for a few hours, so it is very likely that I did not understand something important about macros and modules.

Thank you Marvin,

Renaud

**Comment by Kimundi** [comment]
Well, your issue is that `ROBOT` is defined in a submodule, and thus not visible in your crate root.

Add a `use app::util::globals::ROBOT;` to your `main.rs` module.

**Comment by RenaudParis** [comment]
Ooooh, so that's just it, then? I didn't know I was able to do a use on a
result of a macro. I am sorry... Should have tried that!

Thank you Marvin, I'll change that

Le mar. 22 sept. 2015 à 20:07, Marvin Löbel <notifications@github.com> a
écrit :

**Comment by Kimundi** [comment]
The macro basically just expands to a regular `static` variable with a special type, and access to things outside of a macro body itself follows regular Rust semantic. :)

**Comment by RenaudParis** [comment]
That's what slipped out of my mind I presume ^^ Thank you Marvin for your
kind answer, and sorry for the false alarm!

Le mar. 22 sept. 2015 à 20:17, Marvin Löbel <notifications@github.com> a
écrit :

**Comment by Kimundi** [comment]
No problem, glad I could help. :)
